language: scala

cache:
  directories:
    - $HOME/.m2/repository/
    - $HOME/.ivy2/cache/
    - $HOME/.sbt/boot/

sudo: false

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

branches:
  only:
    - develop

script:
  - ./sbt jcheckStyle
  - ./sbt test
  - ./sbt test -J-Dmsgpack.universal-buffer=true
before_install:
  - wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
  - unzip -qq apache-maven-3.3.9.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
